### ISSUE TITLE
Tests are failing in case of regex match

### ISSUE THREAD

**Issue by pgmanutd** [pgmanutd/data-structures-and-algorithms#2]
**Do you want to request a _feature_ or report a _bug_?**
bug

* **What is the current behavior?**
Getting following error when running ```npm run test arrayDeletion```. This error is coming only in case of regex match
```
 FAIL   unit  packages/data-structures/src/array/basic-operations/__tests__/arrayDeletion.test.ts
  ● Test suite failed to run

    TypeError: vendors.map is not a function

      at Object.<anonymous> (node_modules/ci-info/index.js:9:18)
      at Object.<anonymous> (node_modules/is-ci/index.js:3:18)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.094s
Ran all test suites matching /arrayDeletion/i.
npm ERR! Test failed.  See above for more details.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1.  Run ```npm run test arrayDeletion```

* **What is the expected behavior?**
Tests should run successfully

**Comment by sambunting** [comment]
Hi! Just wanted to say thank you for this issue as it's also helped me fix my own code!

No idea that removing the `json` from `nodeNameMapper` would fix it!

**Comment by pgmanutd** [comment]
> Hi! Just wanted to say thank you for this issue as it's also helped me fix my own code!
> 
> No idea that removing the `json` from `nodeNameMapper` would fix it!

Hey Thanks! 😅 No worries at all. Long time back I did that. Good to know that this small commit helped someone 😄
